version: 4.0.{build}
skip_commits:
  files:
    - '**/*.md'
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable MSBuild terminal logger globally (prevents ESC[2F, ESC[1F, et al)
  MSBUILDTERMINALLOGGER: false
  matrix:
  - job_name: windows
    appveyor_build_worker_image: Visual Studio 2022
  - job_name: linux
    appveyor_build_worker_image: Ubuntu2204
matrix:
  fast_finish: true

for:
  -
    matrix:
      only:
        - job_name: windows
    init:
      # default is: core.autocrlf input
      - git config --global core.autocrlf true
    build_script:
      - ps: dotnet restore --verbosity quiet
      - ps: |
          $version = "4.3.0"
          $versionFile = $version + "." + ${env:APPVEYOR_BUILD_NUMBER}

          if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
              $version = $version + "-PR" + $env:APPVEYOR_PULL_REQUEST_NUMBER
          }

          dotnet pack YAXLib --verbosity minimal --configuration release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath=../artifacts /p:ContinuousIntegrationBuild=true /p:Version=$version /p:FileVersion=$versionFile
    test_script:
      - dotnet test YAXLibTests
    artifacts:
      - path: 'artifacts\*.nupkg'
      - path: 'artifacts\*.snupkg'
    deploy:
    - provider: NuGet
      api_key:
        secure: EYJzInwiRplwe6t578hrjaYfkWw0PnN96TfGbL7cBZDf7r7+nIul/NhX1LaJemER
      on:
        branch: master
  
  -
    matrix:
      only:
        - job_name: linux
    # Run CI tests for YAXLib netstandard2.0, netstandard2.1 target frameworks
    # See further entries and comments in YAXLibTests.csproj
    build_script:
      - dotnet --version
    test_script:
      - echo "Testing YAXLibTests against netstandard2.0"
      - dotnet test YAXLibTests -f net8.0 -p:ForceYAXLibTFM=netstandard2.0 -p:CopyLocalLockFileAssemblies=true -v:minimal
      - dotnet clean YAXLibTests -f net8.0
      - echo "Testing YAXLibTests against netstandard2.1"
      - dotnet test YAXLibTests -f net8.0 -p:ForceYAXLibTFM=netstandard2.1 -p:CopyLocalLockFileAssemblies=true -v:minimal
