name: Build and Test

on:
  push:
    branches: [ master, main, 'version/**', 'pr/**', 'pr-**' ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ master, main, 'version/**', 'pr/**', 'pr-**' ]
    paths-ignore:
      - '**/*.md'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true
  MSBUILDTERMINALLOGGER: false

jobs:
  windows:
    name: Windows Build, Test, Pack and Publish
    runs-on: windows-2022
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Git CRLF
        run: git config --global core.autocrlf true

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Restore packages
        run: dotnet restore --verbosity quiet

      - name: Run unit tests
        run: dotnet test YAXLibTests

      - name: Pack YAXLib
        shell: pwsh
        run: |
          $version = "4.3.0"
          echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV
          $versionFile = "$version.${{ github.run_number }}"
          $prNumber = "${{ github.event.pull_request.number }}"

          if ($prNumber) {
              $version = "$version-PR$prNumber"
          }

          dotnet pack YAXLib --verbosity minimal --configuration release `
            /p:IncludeSymbols=true `
            /p:SymbolPackageFormat=snupkg `
            /p:PackageOutputPath=../artifacts `
            /p:ContinuousIntegrationBuild=true `
            /p:Version=$version `
            /p:FileVersion=$versionFile

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v7
        with:
          name: nuget-packages
          path: |
            artifacts/*.nupkg
            artifacts/*.snupkg

      # Get a short-lived NuGet API key (OIDC -> temp API key)
      - name: NuGet login 
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository_owner == 'YAXLib'
        uses: NuGet/login@v1
        id: login
        with:
           user: ${{ secrets.NUGET_USER }}

      - name: Publish to NuGet
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository_owner == 'YAXLib'
        shell: pwsh
        run: |
          $packagePath = "artifacts/YAXLib.$env:PACKAGE_VERSION.nupkg"
          dotnet nuget push $packagePath --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

  linux:
    name: Linux Test .NET Standard Assets
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Display .NET version
        run: dotnet --version

      - name: Test against netstandard2.0
        run: |
          echo "Testing YAXLibTests against netstandard2.0"
          dotnet test YAXLibTests -f net8.0 -p:ForceYAXLibTFM=netstandard2.0 -p:CopyLocalLockFileAssemblies=true -v:minimal

      - name: Clean before next test
        run: dotnet clean YAXLibTests -f net8.0

      - name: Test against netstandard2.1
        run: |
          echo "Testing YAXLibTests against netstandard2.1"
          dotnet test YAXLibTests -f net8.0 -p:ForceYAXLibTFM=netstandard2.1 -p:CopyLocalLockFileAssemblies=true -v:minimal
